### ISSUE TITLE
"Clean up" The Left Side Sticky Foob GIF

### ISSUE THREAD

**Issue by nevrending** [nevrending/foob#3]
If you notice, the sticky FBK GIF image on the left side of the screen, still has a few parts that's white i.e not transparent.
See below.

![image](https://user-images.githubusercontent.com/4745298/117982636-8d6bd080-b379-11eb-826e-97c034676bbb.png)

Need to check all frames of the GIF and clean them up.
Reduce the file size as well if possible.

File is here: https://github.com/nevrending/foob/blob/master/assets/img/fbk/side.gif

---

If you're unsure how to put changes in GitHub, let me know by commenting below

**Comment by bempfoobq052021** [comment]
All right, I'll clear it!

**Comment by nevrending** [comment]
Closed in #11
