### ISSUE TITLE
Convert All mp3-s to AAC For Better File Sizes

### ISSUE THREAD

**Issue by nevrending** [nevrending/foob#4]
It's best to use AAC for all audio files, since it has a lower file size compared to MP3 with the same bit rate.
And to make sure compatibility across browsers.

https://en.wikipedia.org/wiki/HTML5_audio#Supported_audio_coding_formats

Files are here: https://github.com/nevrending/foob/tree/master/assets/aud/fbk/noises

At the moment, there's one OGG file in there.

---

If you're unsure how to put changes in GitHub, let me know by commenting below

**Comment by bempfoobq052021** [comment]
I'll do it~

**Comment by nevrending** [comment]
Closed in #11
